routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

/*
 * Frontend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    include_route_files(__DIR__.'/frontend/');
});

/*
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend', 'prefix' => BACKEND_URL_NAME, 'as' => 'admin.','middleware' => ['activity']], function () {
    /*
     * These routes need view-backend permission
     * (good if you want to allow more than one group in the backend,
     * then limit the backend features by different roles or permissions)
     *
     * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
     * These routes can not be hit if the password is expired
     */
    include_route_files(__DIR__.'/backend/');
});

app/Models/Backend/Admin.php
<?php

namespace App\Models\Backend;

use App\Notifications\Backend\AdminResetPasswordNotification;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\URL;
use Spatie\Permission\Traits\HasRoles;

class Admin extends Authenticatable
{
    use Notifiable, HasRoles;

    protected $guard_name = 'admin';

    /**
     * Send the password reset notification.
     *
     * @param string $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new AdminResetPasswordNotification($token));
    }

    protected $table = 'admins';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'show_password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getProfileImageUrlAttribute()
    {
        return 'https://ui-avatars.com/api/?name=' . ucfirst(substr($this->attributes['name'], 0, 1)) . '&background=0D8ABC&color=fff';
    }

    public function getEditButtonAttribute()
    {
        return '<a href="' . route('admin.admin-user.edit', $this->id) . '" data-id="' . $this->id . '" class="btn green btn-outline btn-xs"><i class="fa fa-pencil-square-o" data-toggle="tooltip" data-placement="top" title="' . trans('buttons.general.crud.edit') . '"></i></a>';
    }

    /**
     * @return string
     */
    public function getDeleteButtonAttribute()
    {
        return '<a href="javascript:void(0);"
                class="btn red btn-outline btn-xs deleteConfirmation" data-id="' . $this->id . '"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" title="' . trans('buttons.general.crud.delete') . '"></i></a>';
    }

    /**
     * @return string
     */
    public function getActionButtonsAttribute()
    {
        $actionButton = '';

        if (auth()->user()->is_superadmin == 1 || auth()->guard('admin')->user()->can('Edit Admin User')) {
            $actionButton .= $this->edit_button;
        }

        if (auth()->user()->is_superadmin == 1 || auth()->guard('admin')->user()->can('Delete Admin User')) {
            $actionButton .= $this->delete_button;
        }

        return $actionButton;
    }

}

app/Models/Backend/Permission/Traits/Relationship/PermissionRelationship.php
<?php

namespace App\Models\Backend\Permission\Traits\Relationship;

use App\Models\Backend\Admin;

/**
 * Trait RoleRelationship
 * @package App\Models\Backend\GlobalModules\Role\Traits\Relationship
 */
trait PermissionRelationship
{
    public function createdBy()
    {
        return $this->belongsTo(Admin::class, 'created_by');
    }
}

app/Http/Controllers/Backend/AdminUser/AdminUserController.php
<?php

namespace App\Http\Controllers\Backend\AdminUser;

use App\Http\Controllers\Controller;
use App\Repositories\Backend\AdminUser\AdminUserRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use App\Repositories\Backend\Role\RoleRepository;
use App\Models\Backend\Admin;

class AdminUserController extends Controller
{

    /**
     * @var AdminUserRepository
     */
    protected $adminUserRepo;
    protected $roleRepo;

    /**
     * AdminUserRepository constructor.
     * @param AdminUserRepository $adminUser
     */
    public function __construct(AdminUserRepository $adminUserRepo,RoleRepository $roleRepo)
    {
        $this->middleware('auth:admin');
        $this->adminUserRepo = $adminUserRepo;
        $this->roleRepo = $roleRepo;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        try {
            return view(BACKEND_VIEW.'.admin-user.index');
        } catch (\Exception $ex) {
            Log::error($ex->getMessage());
        }
    }

    public function create()
    {
        try {
            $roles = $this->roleRepo->getAll()->pluck('name','id');
            #return view('backend.admin-user.create',compact("roles"));
            return view(BACKEND_VIEW.'.admin-user.create',compact("roles"));
        } catch (\Exception $ex) {
            Log::error($ex->getMessage());
        }
    }

    /**
     * @param StoreAdminUserRequest $request
     * @return mixed
     */
    public function store(Request $request)
    {
        try {
        
            // return  $request->all();
            
            $data= $this->adminUserRepo->create($request->only(                
                'name',
                'email',            
                'mobile_number',            
                'user_type',                
                'password',
                'status',
                'icon'
            ));
            
            toastr()->success('Data has been saved successfully!');

            return redirect()->route('admin.admin-user.index');
        } catch (\Exception $ex) {
            Log::error($ex->getMessage());
        }
    }

    /**
     * @param AdminUser $adminUser
     * @return mixed
     */
    public function edit(Admin $adminUser)
    {
        try {               
            $roles = $this->roleRepo->getAll()->pluck('name','id');
            return view('backend.admin-user.edit',compact("roles"))->withAdminUser($adminUser);            
        } catch (\Exception $ex) {
            Log::error($ex->getMessage());
        }
    }

    /**
     * @param UpdateAdminUserRequest $request
     * @param Admin $adminUser
     * @return mixed
     */
    public function update(Request $request, Admin $adminUser)
    {
        try {
            $this->adminUserRepo->update($adminUser, $request->only(
                'name',
                'email',            
                'mobile_number',            
                'user_type',                
                'password',
                'status',
                'icon'
            ));

            toastr()->success('Data has been updated successfully!');

            return redirect()->route('admin.admin-user.index');
        } catch (\Exception $ex) {
            Log::error($ex->getMessage());
        }
    }

    /**
     * @param Admin $adminUser
     * @return mixed
     */
    public function destroy(Request $request)
    {
        try {
            $adminUser = Admin::findOrFail($request->id);
            if ($adminUser->delete()) {
                return response()->json(['success' => true, 'message' => 'Item deleted successfully']);
            }
            return response()->json(['error' => true, 'message' => 'Internal server error']);
        } catch (\Exception $ex) {
            Log::error($ex->getMessage());
            return response()->json(['error' => true, 'message' => $ex->getMessage()]);
        }
    }

    /**
     * @param Admin $adminUser
     * @return array
     * @throws \Exception
     */
    public function bulkDelete(Admin $adminUser)
    {
        try {
            $delete = $adminUser->whereIn('id', request('data'))->delete();
            if ($delete) {
                return [
                    'success' => '1',
                    'message' => 'Your choosen records has been deleted.'
                ];
            }
        } catch (\Exception $ex) {
            Log::error($ex->getMessage());
        }
    }

    public function bulkAction(Request $request)
    {
        try {
            $actionType = $request->action_type;

            $admin = Admin::query()->whereIn('id', request('data'));

            switch ($actionType) {
                case '0':
                    $admin->update(['status' => 0]);
                    return response()->json(['success' => true, 'message' => 'In-Active record successfully']);
                    break;
                case '1':
                    $admin->update(['status' => 1]);
                    return response()->json(['success' => true, 'message' => 'Active record successfully']);
                    break;
                case '3':
                    $admin->delete();
                    return response()->json(['success' => true, 'message' => 'Delete record successfully']);
                    break;
                default:
                    return response()->json(['error' => true, 'message' => 'No action']);
                    break;
            }
        } catch (\Exception $ex) {
            Log::error($ex->getMessage());
        }
    }

    public function changeStatus(Request $request)
    {
        try {
            $Id = $request->id;
            $admin = Admin::findOrFail($Id);
            $admin->status = $admin->status == 1 ? 0 : 1;
            $admin->save();

            return \response()->json(['success' => true,'message' => 'Change status successfully']);
        }catch(\Exception $ex){
            Log::error($ex->getMessage());
            return \response()->json(['error' => true,'message' => $ex->getMessage()]);
        }
    }
}

app/Http/Controllers/Backend/AdminUser/AdminUserTableController.php
<?php

namespace App\Http\Controllers\Backend\AdminUser;

use App\Http\Controllers\Controller;
use App\Repositories\Backend\AdminUser\AdminUserRepository;
use Illuminate\Support\Facades\Log;
use Yajra\DataTables\Facades\DataTables;

class AdminUserTableController extends Controller
{

    /**
     * @var AdminUserRepository
     */
    protected $adminUserRepo;

    /**
     * AdminUserTableController constructor.
     * @param AdminUserRepository $adminUserRepo
     */
    public function __construct(AdminUserRepository $adminUserRepo)
    {
        $this->adminUserRepo = $adminUserRepo;
    }

    /**
     * @return mixed
     */
    public function __invoke()
    {
        try {
            return DataTables::of($this->adminUserRepo->getForDataTable())
                ->addIndexColumn()
                ->addColumn('parent_id',function($adminUser){
                    return isset($adminUser->parent_id)
                            ? config('backend.backend.adminUser_type.'.$adminUser->parent_id) : '-';
                })
                ->addColumn('action',function($adminUser){
                    return $adminUser->action_buttons;
                })
                ->addColumn('status',function($adminUser){
                    return $adminUser->status == 1
                        ? '<a href="javascript:void(0)" class="status" data-id="'.$adminUser->id.'"><small class="badge badge-success" data-id="'.$adminUser->id.'">Active</small></a>'
                        : '<a href="javascript:void(0)" class="status" data-id="'.$adminUser->id.'"><small class="badge badge-danger">In-active</small></a>';
                })
                ->rawColumns(['id','action','status'])
                ->make(true);
        }catch (\Exception $ex){
            Log::error($ex->getMessage());
        }
    }
}

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BackendController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth:admin');
    }


    public function index(){
        #die(BACKEND_VIEW.'.dashboard');
        return view(BACKEND_VIEW.'.dashboard');
    }
}

app/Http/Controllers/Backend/DemoCrud/DemoCrudTableController.php
<?php

namespace App\Http\Controllers\Backend\DemoCrud;

use App\Http\Controllers\Controller;
use App\Repositories\Backend\DemoCrud\DemoCrudRepository;
use Illuminate\Support\Facades\Log;
use Yajra\DataTables\Facades\DataTables;

class DemoCrudTableController extends Controller
{

    /**
     * @var AdminUserRepository
     */
    protected $demoCrudRepo;

    /**
     * AdminUserTableController constructor.
     * @param AdminUserRepository $demoCrudRepo
     */
    public function __construct(DemoCrudRepository $demoCrudRepo)
    {
        $this->demoCrudRepo = $demoCrudRepo;
    }

    /**
     * @return mixed
     */
    public function __invoke()
    {
        try {
            return DataTables::of($this->demoCrudRepo->getForDataTable())
                ->addIndexColumn()
                ->addColumn('parent_id',function($adminUser){
                    return isset($adminUser->parent_id)
                        ? config('backend.backend.adminUser_type.'.$adminUser->parent_id) : '-';
                })
                ->addColumn('action',function($adminUser){
                    return $adminUser->action_buttons;
                })
                ->addColumn('status',function($adminUser){
                    return $adminUser->status == 1
                        ? '<a href="javascript:void(0)" class="status" data-id="'.$adminUser->id.'"><small class="badge badge-success" data-id="'.$adminUser->id.'">Active</small></a>'
                        : '<a href="javascript:void(0)" class="status" data-id="'.$adminUser->id.'"><small class="badge badge-danger">In-active</small></a>';
                })
                ->rawColumns(['id','action','status'])
                ->make(true);
        }catch (\Exception $ex){
            Log::error($ex->getMessage());
        }
    }
}

app/Http/Controllers/Backend/FrontUser/FrontUserTableController.php
<?php

namespace App\Http\Controllers\Backend\FrontUser;

use App\Http\Controllers\Controller;
use App\Repositories\Backend\FrontUser\FrontUserRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Yajra\DataTables\Facades\DataTables;

class FrontUserTableController extends Controller
{

    /**
     * @var FrontUserRepository
     */
    protected $frontUserRepo;

    /**
     * FrontUserTableController constructor.
     * @param FrontUserRepository $frontUserRepo
     */
    public function __construct(FrontUserRepository $frontUserRepo)
    {
        $this->middleware('auth:admin');
        $this->frontUserRepo = $frontUserRepo;
    }

    /**
     * @return mixed
     */
    public function __invoke(Request $request)
    {
        try {
            $dataTables = $this->frontUserRepo->getForDataTable();

            if (!empty($userType = $request->get('user_type'))) {
                $dataTables->where('user_type',$userType);
            }

            if (!empty($status = $request->has('status'))) {
                $dataTables->where('status',$status);
            }

            if (!empty($request->get('user_package'))) {
                $dataTables->whereHas('activePackage',function ($q) use ($request){
                    $q->where('package_id',$request->get('user_package'));
                });
            }

            return DataTables::of($dataTables)
                ->addIndexColumn()
                ->addColumn('parent_id',function($frontUser){
                    return isset($frontUser->parent_id)
                        ? config('backend.backend.frontUser_type.'.$frontUser->parent_id) : '-';
                })
                ->editColumn('user_type',function($frontUser){
                    return !empty($frontUser->user_type) ? config('backend.backend.package_user_type.'.$frontUser->user_type) : '-';
                })
                ->addColumn('live_property',function($frontUser){
                    return $frontUser->userProperty->count();
                })
                ->addColumn('response',function($frontUser){
                    return 0;
                })
                ->addColumn('created_at',function($frontUser){
                    return globalDateFormat($frontUser->created_at);
                })
                ->addColumn('action',function($frontUser){
                    return $frontUser->action_buttons;
                })
                ->addColumn('status',function($frontUser){
                    return $frontUser->status == 1
                        ? '<a href="javascript:void(0)" class="status" data-id="'.$frontUser->id.'"><small class="badge badge-success" data-id="'.$frontUser->id.'">Active</small></a>'
                        : '<a href="javascript:void(0)" class="status" data-id="'.$frontUser->id.'"><small class="badge badge-danger">In-active</small></a>';
                })
                ->addColumn('created_by', function ($frontUser) {
                    return !empty($frontUser->createdBy->name) ? $frontUser->createdBy->name : $frontUser->created_by;
                })
                ->rawColumns(['id','action','status'])
                ->make(true);
        }catch (\Exception $ex){
            Log::error($ex->getMessage());
        }
    }
}

resources/views/backend/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            @if(\Request::route()->getName() == 'admin.auth.login' || \Request::route()->getName() == 'admin.auth.register')
                                <a class="nav-link" href="{{ route('admin.auth.login') }}">{{ __('Login') }}</a>
                            @else
                                <a class="nav-link" href="{{ route('admin.auth.login') }}">{{ __('Login') }}</a>
                            @endif
                        </li>
                        <li class="nav-item">
                            @if(\Request::route()->getName() == 'admin.auth.login' || \Request::route()->getName() == 'admin.auth.register')
                                <a class="nav-link" href="{{ route('admin.auth.register') }}">{{ __('Register') }}</a>
                            @else
                                <a class="nav-link" href="{{ route('admin.auth.register') }}">{{ __('Register') }}</a>
                            @endif
                        </li>
                    @else
                        @if(\Illuminate\Support\Facades\Auth::guard('admin')->check())
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::guard('admin')->user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('admin.auth.logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('admin.auth.logout') }}" method="POST"
                                          style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endif
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
{{--        {!! Breadcrumbs::render() !!}--}}
        @yield('content')
    </main>
</div>
</body>
</html>

resources/views/backend/layouts/app_auth.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{app_name().' | Log in'}}</title>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{config('site-config.backend_assets_url')}}/dist/css/adminlte.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{config('site-config.backend_assets_url')}}/plugins/iCheck/square/blue.css">
    <link href="{{ url('assets/backend/custom.css') }}" rel="stylesheet">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ _get_favicon() }}">
</head>
<body class="hold-transition register-page">
<div id="app">
        @yield('content')
</div>
<!-- jQuery -->
<script src="{{config('site-config.backend_assets_url')}}/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="{{config('site-config.backend_assets_url')}}/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
{{-- Validation --}}
<script src="{{ asset('assets/common/ex_plugins/jquery-validation-1.19.1/dist/jquery.validate.js') }}"></script>

@section("page_vendors")
@show
@section("page_script")
@show
</body>

</html>

resources/views/backend/layouts/auth-form-status.blade.php
@if (session('success'))
	<div class="alert alert-success" role="alert">
		<i class="flaticon-tick-inside-circle"></i>{{ session('success') }}
	</div>
@endif

@if (session('error'))
	<div class="alert alert-danger" role="alert">
		<i class="flaticon-alert-1"></i>{{ session('error') }}
	</div>
@endif

@if (session('errors') && count($errors) > 0)
    <div class="alert alert-danger" role="alert">
        <h6 style="text-align: center; "><strong>Whoops! There were some problems with your input.</strong></h6>
        <div style="display: flex; align-items: center;">
            <i class="flaticon-alert-1"></i>
            <ul>
                @foreach ($errors->all() as $error)
                	<li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    </div>
@endif

resources/views/backend/layouts/footer.blade.php
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->
<footer class="main-footer">
    <strong>Copyright © {{ date('Y',strtotime(\Carbon\Carbon::now())) }} <a href="/">{{ app_name() }}</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 3.1.0
    </div>
</footer>

resources/views/backend/layouts/header.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown" style="width: 170px">
            <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
                <div class="user-panel image" style="position: absolute;overflow: -moz-scrollbars-none; left: -23px">
                    <img src="{{ loggedUser()->profile_image_url }}"
                         class="img-circle elevation-2" alt="User Image">
                </div>
                <div style="margin-top: 5px">
                    <span>{{ loggedUser()->name }}</span>
                    <i class="right fa fa-angle-down"></i>
                </div>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <i class="fa fa-user-circle-o mr-2"></i> My Profile
                </a>
                <a href="#" class="dropdown-item">
                    <i class="fa fa-key mr-2"></i> Change Password
                </a>
                <div class="dropdown-divider"></div>
                <a href="{{ route('admin.auth.logout') }}" class="dropdown-item"
                   onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                    <i class="fa fa-lock mr-2"></i> Logout
                    <form id="logout-form" action="{{ route('admin.auth.logout') }}" method="POST"
                          style="display: none;">
                        @csrf
                    </form>
                </a>
                <div class="dropdown-divider"></div>
                {{--                <a class="nav-link" href="{{ route('admin.auth.logout') }}"--}}
                {{--                   onclick="event.preventDefault(); document.getElementById('logout-form').submit();">--}}
                {{--                    Logout--}}

                {{--                </a>--}}
            </div>
        </li>
        <li class="nav-item">

        </li>
    </ul>
</nav>
<!-- /.navbar -->

resources/views/backend/layouts/master.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    @yield('title')
    <base href="{{url('/')}}/bbadmin/">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <script>
        var CSRFTOKEN = '{{ csrf_token() }}';
    </script>
    {{-- Include styles files--}}
    @include(BACKEND_VIEW.'.layouts.styles')
    @yield('after-styles')
</head>
<body class="hold-transition sidebar-mini" ng-app="myApp">
<div class="wrapper">
    {{--Include Navbar --}}
    @include(BACKEND_VIEW.'.layouts.header')
    <!-- Main Sidebar Container -->
    @include(BACKEND_VIEW.'.layouts.sidebar')
    @yield('content')
    <!-- Footer Container-->
    @include(BACKEND_VIEW.'.layouts.footer')
</div>
<!-- ./wrapper -->

{{--Include scripts files--}}
@include(BACKEND_VIEW.'.layouts.scripts')
@yield('after-scripts')
</body>
</html>